services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: rta-kafka
    hostname: kafka
    ports:
      - "9092:9092"    # client connections from your Mac
      - "9093:9093"    # controller quorum
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      # The image will auto-format logs if CLUSTER_ID is set.
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
    volumes:
      - kafka_data:/var/lib/kafka/data

  postgres:
    image: postgres:16-alpine
    container_name: rta-postgres
    environment:
      - POSTGRES_USER=ads
      - POSTGRES_PASSWORD=ads
      - POSTGRES_DB=adsdb
    ports: ["5433:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: rta-kafka-ui
    depends_on: [kafka]
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports: ["8080:8080"]

volumes:
  kafka_data:
  pg_data:
