services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: rta-zk
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: rta-kafka
    depends_on: [zookeeper]
    ports:
      - "9092:9092"   # host access from your Mac
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # two listeners: external for host, internal for other containers
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT_INTERNAL"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16-alpine
    container_name: rta-postgres
    environment:
      - POSTGRES_USER=ads
      - POSTGRES_PASSWORD=ads
      - POSTGRES_DB=adsdb
    ports: ["5433:5432"]  # host port 5433 to avoid conflicts
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: rta-kafka-ui
    depends_on: [kafka]
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092   # <-- internal listener
    ports: ["8080:8080"]

volumes:
  pg_data:
