name: demo-seed

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install "psycopg[binary]==3.2.1"

      - name: Upsert last N windows into Neon
        env:
          NEON_HOST_DIRECT: ${{ secrets.NEON_HOST_DIRECT }}   # direct host (no -pooler)
          NEON_DB:         ${{ secrets.NEON_DB }}
          NEON_USER:       ${{ secrets.NEON_USER }}
          NEON_PASS:       ${{ secrets.NEON_PASS }}
          NUM_WINDOWS:     "36"
        run: |
          python -V
          python -c "import pathlib; p=pathlib.Path('cloud/seed_worker.py'); print('Seeder exists:', p.exists()); print('--- SQL preview ---'); print([l for l in p.read_text().splitlines() if 'INSERT INTO campaign_agg' in l or 'VALUES (' in l][0:3])"
          python cloud/seed_worker.py


